root_dir: /data1/1/code/datasets/fs/finefs/
#root_dir: /data1/1/code/datasets/fs/fs1000/
#root_dir: /data1/1/code/datasets/fs/fisv/

vocab_file: /data1/1/code/helping/ImageBind/imagebind/bpe/bpe_simple_vocab_16e6.txt.gz
checkpoint_path:

# multi batch size cause miss match
batch_size: 1
learning_rate: 2e-5

vocab_size: 49413
content_length: 248
embed_dim: 1024

vaf_num_blocks: 8
vaf_num_heads: 4
num_blocks: 32
num_heads: 16
concat_strategy: embed_hack
#concat_strategy: insert
epoch: 50

threshold: 0.6
prompt: "How did the athlete perform in the show?"
